### ISSUE TITLE
Use with RadioRA 2

### ISSUE THREAD

**Issue by draperw** [sushilks/node-red-contrib-lutron#2]
I have this palette working fine with my Caséta system. I'm trying to get it to work with my RadioRA 2 system. Unfortunately it doesn't work. And I can't figure out why as the Telnet login process, password,  and commands are the same for the different systems. 

When manually logging into the Telnet interface from a terminal window everything looks the same except for a single thing. In Caséta after logging in the next line is GNET>. In RadioRA 2 there is a line feed between the password entry and the GNET> prompt.

The Node-Red log:

4/5/2020 14:12 | telent error
4/5/2020 14:12 | telnet close
4/5/2020 14:12 | [31mUnhandled rejection Error: Cannot connect
4/5/2020 14:12 | at Socket.socket.setTimeout (/data/node_modules/telnet-client/lib/index.js:85:25)
4/5/2020 14:12 | at Object.onceWrapper (events.js:286:20)
4/5/2020 14:12 | at Socket.emit (events.js:198:13)
4/5/2020 14:12 | at Socket._onTimeout (net.js:443:8)
4/5/2020 14:12 | at ontimeout (timers.js:436:11)
4/5/2020 14:12 | at tryOnTimeout (timers.js:300:5)
4/5/2020 14:12 | at listOnTimeout (timers.js:263:5)
4/5/2020 14:12 | at Timer.processTimers (timers.js:223:10)[0m

**Comment by sushilks** [comment]
The telnet connection is handled by "telnet-client" library, Looks like it's unable to process the interaction with RadioRA.
Few things you can try
- Bump up the telnet-client library to current version 1.2.11 (In package.json its set to 0.16.1) you can bump it up by running "npm i telnet-client@1.2.11"
- If that does not work, try tweaking the parameters on the library. The parameters are listed at https://github.com/mkozjak/node-telnet-client#api
   Specifically look at loginPrompt, initialLFCR.

If you are able to fix the code in a way that works for both Caseta and RatioRA please submit an Pull Request as well.

**Comment by draperw** [comment]
Thanks, I've tried some of that. I've raised an issue on the telnet client GitHub page.

**Comment by draperw** [comment]
Also, it's a bit odd. The Telnet connection is working in Caséta as shown by data appearing in the debug node output. But those same errors are being generated. So they don't seem to be fatal for Caséta.

**Comment by parish99** [comment]
Been a year and a half, has there been any update to getting this working with RA2, using the main repeater or the pro hub?

**Comment by sushilks** [comment]
I did not have a ra2 system so cold not debug it, I recently got an ra2 select system and have verified that the code works with it.
